"""Programmatic API for Loom - usable by Claude or scripts."""

from pathlib import Path
from datetime import datetime
from tree import Tree, Node
from generator import Generator, GenerationConfig, perplexity

TREES_DIR = Path(__file__).parent / "trees"

ANALYSIS_MODEL = "claude-sonnet-4-6"


def model_label(model: str) -> str:
    """Human-readable name for a generation endpoint.

    Strips the org prefix and the trailing deployment hash so
    "sviteri/Qwen/Qwen3-30B-A3B-Base-3737eb6e" -> "Qwen3-30B-A3B-Base".
    """
    name = model.rstrip("/").split("/")[-1]
    base, _, suffix = name.rpartition("-")
    if base and len(suffix) >= 6 and all(c in "0123456789abcdef" for c in suffix.lower()):
        name = base
    return name


def analyze_continuation(prefix_text: str, continuation_text: str, model_name: str = "the base model") -> str:
    """Use Claude to analyze how the base model interpreted a prefix.

    Returns the analysis text. Raises if prefix or continuation is empty so
    callers can surface a friendly message. model_name is the generator that
    produced the continuation, so the prompt describes its own evidence
    faithfully regardless of which endpoint is configured.
    """
    import anthropic

    if not continuation_text:
        raise ValueError("No text to analyze at this node.")
    if not prefix_text:
        raise ValueError("No prefix text - this is the root node.")

    prompt = f"""Analyze this text generation. A language model ({model_name}) was given a prefix and generated a continuation.

PREFIX:
{prefix_text}

CONTINUATION (generated by {model_name}):
{continuation_text}

Provide a brief analysis (2-3 sentences each):
1. **Prefix**: What is happening/being discussed in the prefix?
2. **Continuation**: What does the continuation add or where does it take the text?
3. **{model_name}'s interpretation**: Based on how the continuation follows the prefix, what does {model_name} seem to think the text is about or where it should go?"""

    client = anthropic.Anthropic()
    response = client.messages.create(
        model=ANALYSIS_MODEL,
        max_tokens=500,
        messages=[{"role": "user", "content": prompt}]
    )
    return response.content[0].text


class Loom:
    """Non-interactive API for tree-based text exploration."""

    def __init__(
        self,
        model: str | None = None,
        load_path: Path | None = None,
        config: GenerationConfig | None = None,
        prompt: str | None = None,
    ):
        """Initialize Loom with optional config/model override and starting tree.

        Pass `config` to set max_tokens/temperature/etc. (the CLI does this);
        `model` overrides just the endpoint. `load_path` loads an existing tree,
        else `prompt` seeds the root text, else an empty tree.
        """
        config = config or GenerationConfig()
        if model:
            config.model = model
        self.generator = Generator(config)

        if load_path and load_path.exists():
            self.tree = Tree.load(load_path)
        elif prompt:
            self.tree = Tree(root_text=prompt)
        else:
            self.tree = Tree()

        self.current_node = self.tree.root
        self._last_branches: list = []  # list[Generation] from the last generate()

    def write(self, text: str) -> str:
        """Write text at current position."""
        if not self.current_node.text and self.current_node == self.tree.root:
            self.current_node.text = text
        else:
            new_node = self.tree.add_branch(self.current_node.id, text)
            self.current_node = new_node
        return f"Written. Now at node {self.current_node.id}, depth {self.depth}"

    def continue_branch(self, max_tokens: int | None = None) -> str:
        """Generate a single continuation and follow it."""
        full_text = self.tree.get_full_text(self.current_node.id)
        if not full_text:
            return "Error: No text to continue from. Write something first."

        gen = self.generator.generate_single(full_text, max_tokens=max_tokens)
        new_node = self.tree.add_branch(self.current_node.id, gen.text, logprobs=gen.logprobs)
        self.current_node = new_node
        return f"Generated:\n{gen.text}\n\nNow at node {self.current_node.id}, depth {self.depth}"

    def generate(self, n: int = 3, max_tokens: int | None = None) -> str:
        """Generate multiple branches and store them for selection."""
        full_text = self.tree.get_full_text(self.current_node.id)
        if not full_text:
            return "Error: No text to continue from. Write something first."

        self._last_branches = self.generator.generate_continuations(
            full_text, num_branches=n, max_tokens=max_tokens
        )

        result = f"Generated {n} branches:\n\n"
        for i, gen in enumerate(self._last_branches):
            preview = gen.text[:200].replace('\n', ' ')
            if len(gen.text) > 200:
                preview += "..."
            ppl = perplexity(gen.logprobs)
            tag = f" (ppl {ppl:.1f})" if ppl is not None else ""
            result += f"[{i + 1}]{tag} {preview}\n\n"
        result += "Use select(n) to choose one, or select_all() to add all."
        return result

    def select(self, branch_num: int) -> str:
        """Select a generated branch by number (1-indexed)."""
        idx = branch_num - 1
        if not self._last_branches:
            return "Error: No branches to select. Run generate() first."
        if idx < 0 or idx >= len(self._last_branches):
            return f"Error: Invalid branch number. Choose 1-{len(self._last_branches)}."

        gen = self._last_branches[idx]
        new_node = self.tree.add_branch(self.current_node.id, gen.text, logprobs=gen.logprobs)
        self.current_node = new_node
        self._last_branches = []
        return f"Selected branch {branch_num}. Now at node {self.current_node.id}, depth {self.depth}"

    def add_branches(self, branch_nums: list[int] | None = None) -> str:
        """Add generated branches as children without moving the cursor.

        branch_nums are 1-indexed; None adds all. Out-of-range numbers are
        ignored. Clears the pending branches afterward.
        """
        if not self._last_branches:
            return "Error: No branches to select. Run generate() first."

        if branch_nums is None:
            chosen = list(self._last_branches)
        else:
            chosen = [self._last_branches[n - 1] for n in branch_nums
                      if 1 <= n <= len(self._last_branches)]

        for gen in chosen:
            self.tree.add_branch(self.current_node.id, gen.text, logprobs=gen.logprobs)

        self._last_branches = []
        return f"Added {len(chosen)} branches as children of node {self.current_node.id}"

    def select_all(self) -> str:
        """Add all generated branches as children."""
        return self.add_branches(None)

    def split(self, char_index: int, keep_remainder: bool = False) -> str:
        """Split current node's text at character index.

        Trims text to first char_index characters. If keep_remainder=True,
        creates a child node with the remainder. Otherwise discards it.
        """
        text = self.current_node.text
        if not text:
            return "Error: No text to split."
        if char_index <= 0:
            return "Error: char_index must be positive."
        if char_index >= len(text):
            return f"Error: char_index {char_index} >= text length {len(text)}."

        before = text[:char_index]
        after = text[char_index:]

        self.current_node.text = before
        self.current_node.analysis = None  # Clear stale analysis
        self.current_node.logprobs = None  # logprobs no longer match the trimmed text

        if keep_remainder and after.strip():
            child = self.tree.add_branch(self.current_node.id, after)
            return f"Split at {char_index}. Kept {len(before)} chars, remainder ({len(after)} chars) moved to child {child.id}."
        else:
            return f"Split at {char_index}. Kept {len(before)} chars, discarded {len(after)} chars. Ready to regenerate."

    def trim(self, keep_chars: int) -> str:
        """Shorthand: keep only the first N characters of current node."""
        return self.split(keep_chars, keep_remainder=False)

    def split_and_branch(self, char_index: int) -> str:
        """Split current node at char_index and open a fresh empty sibling.

        The text after char_index becomes one child (the path you already
        took); a new empty child is added beside it and becomes current, so you
        can write or generate an alternative continuation from that point. This
        is the in-text "branch here" action used by the GUI.
        """
        split_node_id = self.current_node.id
        result = self.split(char_index, keep_remainder=True)
        if result.startswith("Error"):
            return result
        new_node = self.tree.add_branch(split_node_id, "")
        self.current_node = new_node
        return f"Split at {char_index} and opened new sibling branch {new_node.id}."

    def branch_with_text(self, char_index: int, seed_text: str) -> str:
        """Fork before `char_index` and seed the new sibling with `seed_text`.

        Like `split_and_branch`, but the new branch starts with given text
        instead of empty. Used by the candidates bar: clicking an alternative
        next-token forks the path right before that position and begins the new
        branch with the chosen token, ready to continue generating from it.

        `char_index == 0` means "before the first token of the current node",
        i.e. diverge at the parent — so the new branch becomes a sibling of the
        current node rather than splitting it.
        """
        if not seed_text:
            return "Error: no seed text."
        if char_index == 0:
            parent_id = self.current_node.parent_id
            if parent_id is None:
                return "Error: can't fork before the root."
            new_node = self.tree.add_branch(parent_id, seed_text)
            self.current_node = new_node
            return f"Forked a sibling branch {new_node.id} seeded with {seed_text!r}."
        split_node_id = self.current_node.id
        result = self.split(char_index, keep_remainder=True)
        if result.startswith("Error"):
            return result
        new_node = self.tree.add_branch(split_node_id, seed_text)
        self.current_node = new_node
        return f"Forked at {char_index}; new branch {new_node.id} seeded with {seed_text!r}."

    def score_node(self, node_id: str | None = None,
                   with_candidates: bool = True, candidate_cap: int = 120) -> str:
        """Compute per-token logprobs for an existing node via an echo pass.

        Conditions on the node's real prefix (the path from root), so the
        coloring matches what the model would have assigned. Lets human-written
        or imported text — including the root seed — be colored by surprisal.

        With `with_candidates` (the default), it also fetches the top-k next-token
        candidates at each position so the hover bar works on human text too; this
        costs one extra 1-token request per token (concurrent, capped at
        `candidate_cap`). Pass `with_candidates=False` for coloring only.
        """
        node = self.tree.get_node(node_id) if node_id else self.current_node
        if node is None:
            return "Error: node not found."
        if not node.text:
            return "Nothing to score (empty node)."
        path = self.tree.get_path_to_node(node.id)
        prefix = "".join(n.text for n in path[:-1])
        gen = self.generator.score(prefix, node.text,
                                   with_candidates=with_candidates, candidate_cap=candidate_cap)
        if gen.logprobs is None:
            return "Error: couldn't align scored tokens to the text."
        node.logprobs = gen.logprobs
        ppl = perplexity(gen.logprobs)
        return f"Scored node {node.id}" + (f" (ppl {ppl:.1f})" if ppl is not None else "")

    def score_tree(self, with_candidates: bool = False, candidate_cap: int = 120) -> str:
        """Score every node that has text but no logprobs yet.

        Defaults to coloring only (`with_candidates=False`): fetching candidates
        for every node of a large tree multiplies the request count, so it's
        opt-in here even though `score_node` enables it.
        """
        scored = 0
        for node in list(self.tree._node_index.values()):
            if node.text and not node.logprobs:
                prefix = "".join(n.text for n in self.tree.get_path_to_node(node.id)[:-1])
                gen = self.generator.score(prefix, node.text,
                                           with_candidates=with_candidates, candidate_cap=candidate_cap)
                if gen.logprobs is not None:
                    node.logprobs = gen.logprobs
                    scored += 1
        return f"Scored {scored} node(s)."

    def up(self) -> str:
        """Go to parent node."""
        if self.current_node.parent_id:
            parent = self.tree.get_node(self.current_node.parent_id)
            if parent:
                self.current_node = parent
                return f"Moved to parent node {self.current_node.id}, depth {self.depth}"
        return "Already at root."

    def root(self) -> str:
        """Go to root node."""
        self.current_node = self.tree.root
        return f"At root node {self.current_node.id}"

    def goto(self, node_id: str) -> str:
        """Go to a specific node by ID."""
        node = self.tree.get_node(node_id)
        if node:
            self.current_node = node
            return f"Moved to node {node_id}, depth {self.depth}"
        return f"Error: Node {node_id} not found."

    def child(self, n: int) -> str:
        """Go to nth child (1-indexed)."""
        idx = n - 1
        if idx < 0 or idx >= len(self.current_node.children):
            if not self.current_node.children:
                return "No children at this node."
            return f"Error: Invalid child number. Choose 1-{len(self.current_node.children)}."
        self.current_node = self.current_node.children[idx]
        return f"Moved to child {n}, node {self.current_node.id}, depth {self.depth}"

    def siblings(self, node_id: str | None = None) -> list[Node]:
        """The children of a node's parent, in order (the node + its siblings).

        Empty for the root. Shared by both UIs so sibling logic lives in one
        place; the GUI marks branch points with it and the TUI cycles with it.
        """
        node = self.tree.get_node(node_id) if node_id else self.current_node
        if not node or not node.parent_id:
            return []
        parent = self.tree.get_node(node.parent_id)
        return list(parent.children) if parent else []

    def select_sibling(self, offset: int = 1) -> str:
        """Move to the sibling `offset` positions away, wrapping around.

        offset=+1 is the next sibling (GUI click), -1 the previous (shift-click).
        """
        sibs = self.siblings()
        if len(sibs) < 2:
            return "No siblings to cycle at this node."
        idx = next((i for i, c in enumerate(sibs) if c.id == self.current_node.id), 0)
        target = (idx + offset) % len(sibs)
        self.current_node = sibs[target]
        return f"Moved to sibling {target + 1}/{len(sibs)}, node {self.current_node.id}"

    def analyze(self) -> str:
        """Analyze current node with Claude."""
        path = self.tree.get_path_to_node(self.current_node.id)
        prefix_text = "".join(n.text for n in path[:-1])

        try:
            analysis = analyze_continuation(
                prefix_text, self.current_node.text, model_label(self.generator.config.model)
            )
        except ValueError as e:
            return f"Error: {e}"

        self.current_node.analysis = analysis
        return analysis

    def state(self) -> str:
        """Get current state as readable text."""
        path = self.tree.get_path_to_node(self.current_node.id)
        prefix_text = "".join(n.text for n in path[:-1])
        current_text = self.current_node.text or ""

        result = f"=== LOOM STATE ===\n"
        result += f"Node: {self.current_node.id} | Depth: {self.depth} | Children: {len(self.current_node.children)}\n\n"

        if prefix_text:
            result += f"--- PREFIX ---\n{prefix_text}\n\n"
        if current_text:
            result += f"--- CURRENT (this node) ---\n{current_text}\n\n"

        if self.current_node.analysis:
            result += f"--- ANALYSIS ---\n{self.current_node.analysis}\n\n"

        if self.current_node.children:
            result += f"--- CHILDREN ---\n"
            for i, child in enumerate(self.current_node.children):
                preview = child.text[:80].replace('\n', ' ')
                if len(child.text) > 80:
                    preview += "..."
                result += f"[{i + 1}] {child.id}: {preview}\n"

        return result

    def full_text(self) -> str:
        """Get the full text from root to current node."""
        return self.tree.get_full_text(self.current_node.id)

    def save(self, filepath: str | None = None) -> str:
        """Save tree to file. Uses trees/ folder with datetime name by default."""
        if filepath is None:
            TREES_DIR.mkdir(exist_ok=True)
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filepath = TREES_DIR / f"loom_{timestamp}.json"
        else:
            filepath = Path(filepath)
        self.tree.save(filepath)
        return f"Saved to {filepath}"

    def load(self, filepath: str) -> str:
        """Load tree from file. Checks trees/ folder if not found directly."""
        path = Path(filepath)
        if not path.exists():
            # Try in trees folder
            trees_path = TREES_DIR / filepath
            if trees_path.exists():
                path = trees_path
            else:
                return f"Error: File {filepath} not found."
        self.tree = Tree.load(path)  # Tree.load already builds the node index
        self.current_node = self.tree.root
        return f"Loaded from {path}. At root node."

    def list_trees(self) -> str:
        """List saved trees in the trees folder."""
        if not TREES_DIR.exists():
            return "No trees folder found."
        files = sorted(TREES_DIR.glob("*.json"), key=lambda p: p.stat().st_mtime, reverse=True)
        if not files:
            return "No saved trees found."
        result = "=== SAVED TREES ===\n"
        for f in files:
            mtime = datetime.fromtimestamp(f.stat().st_mtime).strftime("%Y-%m-%d %H:%M")
            result += f"{f.name} ({mtime})\n"
        return result

    @property
    def depth(self) -> int:
        """Current depth in tree."""
        return len(self.tree.get_path_to_node(self.current_node.id)) - 1

    def tree_view(self) -> str:
        """Get a text representation of the tree structure."""
        def _render(node: Node, indent: int = 0) -> str:
            marker = ">>> " if node.id == self.current_node.id else ""
            preview = node.text[:50].replace('\n', ' ') if node.text else "[empty]"
            if node.text and len(node.text) > 50:
                preview += "..."
            result = "  " * indent + f"{marker}[{node.id}] {preview}\n"
            for child in node.children:
                result += _render(child, indent + 1)
            return result

        return f"=== TREE ===\n{_render(self.tree.root)}"
